import { useParams, useRouter} from "next/router";
import Head from 'next/head';
import Link from 'next/link';
import Hero from '../../components/Hero';
import Download from "../../components/Download";

const Story = ()=>{
    const router = useRouter();
    const { sid } = router.query;
    // const abc = useParams();
  
    return(
        <div style={{ backgroundColor: `black` }}>
            <Head>
                <Link href='/'><title>Collecto</title></Link>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div style={{fontSize: '100px'}}>sid</div>
          
            {/* <Hero heading='Home' message='Want to learn about copyright-free images ? Click on Learn More button.'/> */}
        </div>
    

        // <div>
        //     <div>
        //         <h1>aha</h1>
        //         <p>{sid}</p>
        //     </div>
        //     {/* <Hero heading='Home' message='Want to learn about copyright-free images ? Click on Learn More button.'/> */}
        // </div>
        
    )
    
}

export default Story